[workspace]
members = [
    "arwa",
    "arwa_macro",
    "arwa_parse",
    "examples/animation_frame",
    "examples/console",
    "examples/custom_events",
    "examples/events",
    "examples/geolocation",
    "examples/media_element",
]
